name: Create AutoInstall ISO

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Image Version'     
        required: true
        default: '22.04.2'

jobs:
  create_iso:
    runs-on: ubuntu-latest
    steps:
      - name: Install apt dependencies with caching
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: xorriso sed curl gpg isolinux
          version: 1.0

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout ubuntu-autoinstall-generator.sh from covertsh
        uses: actions/checkout@v3
        with:
          repository: covertsh/ubuntu-autoinstall-generator
          sparse-checkout: |
            ubuntu-autoinstall-generator.sh
          sparse-checkout-cone-mode: false
          path: generator

      - name: Download ISO
        run: |
          wget -q https://releases.ubuntu.com/${{ github.event.inputs.version }}/ubuntu-${{ github.event.inputs.version }}-live-server-amd64.iso -O /tmp/ubuntu-${{ github.event.inputs.version }}-live-server-amd64.iso

      - name: Create AutoInstall ISO
        run: |
          chmod +x ./generator/ubuntu-autoinstall-generator.sh
          bash ./generator/ubuntu-autoinstall-generator.sh \
          -a -k \
          -s /tmp/ubuntu-${{ github.event.inputs.version }}-live-server-amd64.iso \
          -u ./main/ubuntu/templates/user-data \
          -m ./main/ubuntu/templates/meta-data \
          -d /tmp/autoinstall-ubuntu-${{ github.event.inputs.version }}-live-server-amd64.iso

