name: Netboot resources

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Ubuntu Live Server Version'     
        required: true
        default: '22.04.2'

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Get version as major/minor
        uses: terradatum/semver-action
        with:
          version: v1.0.0
        id: semver_parts

      - name: Install apt dependencies with caching
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: genisoimage mtools pxelinux syslinux-common
          version: 1.0

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install distro-info ubuntu-server-netboot

      - name: extract vmlinuz and initrd from ISO
        run: ubuntu-server-netboot --url https://old-releases.ubuntu.com/${{ steps.semver_parts.outputs.major }}.${{ steps.semver_parts.outputs.minor }}/ubuntu-${{ steps.semver_parts.outputs.version }}-live-server-amd64.iso --out-dir /tmp

      - name: upload vmlinuz and initrd to release
        uses: softprops/action-gh-release@v1
        with:
          name: ubuntu-${{ steps.semver_parts.outputs.version }}-live-server-amd64.iso
          tag_name: ${{ steps.semver_parts.outputs.version }}
          fail_on_unmatched_files: true
          files: |
            /tmp/ubuntu-installer/casper/vmlinuz
            /tmp/ubuntu-installer/casper/initrd
            /tmp/ubuntu-${{ steps.semver_parts.outputs.version }}-live-server-amd64.iso
